language: ruby
rvm:
  - 2.2.2
  - rbx-2.5.7
  - ruby-head
  - jruby-1.7.20.1
  - jruby-9.0.0.0.rc1
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.0.0.rc1
before_script:
  - mysql -e 'create database milestone_test;'
  - psql -c 'create database milestone_test' -U postgres
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
