language: ruby
rvm:
  - 2.1.0
  - ruby-head
  - rbx-2.2.4

before_script:
  - mysql -e 'create database milestone_test;'
  - mv 'config/database.travis.yml' 'config/database.yml'
  - mv 'config/initializers/secret_token.travis.rb' 'config/initializers/secret_token.rb'
