language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode

before_script:
  - mysql -e 'create database milestone_test;'
  - mv 'config/database.travis.yml' 'config/database.yml'
  - mv 'config/initializers/secret_token.travis.rb' 'config/initializers/secret_token.rb'
