language: ruby
rvm:
  - 2.2.2

before_script:
  - mysql -e 'create database milestone_test;'
  - mv 'config/database.travis.yml' 'config/database.yml'
  - mv 'config/secrets.travis.yml' 'config/secrets.yml'
