language: ruby
rvm:
  - 2.2.2

before_script:
  - mysql -e 'create database milestone_test;'
  - psql -c 'create database milestone_test' -U postgres
  - cp config/database.yml.travis config/database.yml
