language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - mysql -e 'create database milestone_test;'
  - psql -c 'create database milestone_test' -U postgres
  - cp config/database.travis.yml config/database.yml
